CREATE TABLE REPORT (
    ID INTEGER NOT NULL,
    NAME VARCHAR(30) NOT NULL,
    SQL_BASE VARCHAR(200) NOT NULL,
	ACTIVE SMALLINT NOT NULL);

CREATE TABLE INPUTS (
    ID INTEGER NOT NULL,
    REPORT_ID INTEGER NOT NULL,
    INP_TYPE INTEGER NOT NULL,
    EXHIBITION_NAME VARCHAR(30),
    COLUMN_NAME VARCHAR(30) NOT NULL,
	NOT_NULL SMALLINT NOT NULL);
	
INSERT INTO REPORT VALUES(1,'REPORT TEST','SELECT * FROM REPORT [WHERE]',1);
INSERT INTO INPUTS VALUES(1,1,1,'Report Name','COLUMN_NAME',0);
